### ISSUE TITLE
custom environment variables for XCUITest

### ISSUE THREAD

**Issue by mchandr5** [saucelabs/saucectl-xcuitest-example#18]
Is there a way to pass custom env variables to saucectl that I use in my XCUITest. Currently, I see the env parameter in saucectl config yaml shows as not applicable for XCUITests and Espresso. There are options in Xcode TestPlan / Schemes to use environment variable if needed. Any help on this is appreciated.

**Comment by alexplischke** [comment]
That is unfortunately not possible at the moment.

**Comment by mchandr5** [comment]
@alexplischke - Can it be consider as a feature request?

**Comment by alexplischke** [comment]
Yup, for sure! (cc: @wswebcreation )

**Comment by wswebcreation** [comment]
Hi @mchandr5 

Can you send me an email on wim.selles@saucelabs.com so we can get in contact with each other about this
